version: "2"
services:
  varnish:
    image: meanbee/magento2-varnish:latest
    environment:
      - VIRTUAL_HOST=localhost #magento2.docker
      - VIRTUAL_PORT=80
      - HTTPS_METHOD=noredirect
    ports:
      - 80
    links:
      - web

  web:
    image: magento2-nginx:1.9
    build: ./nginx
    ports:
      - 80:80
    links:
      - fpm
      - db
      - es
    volumes_from:
      - appdata
    env_file:
      - ./global.env
    # environment:
      # - VIRTUAL_HOST=magento2.docker
      # - VIRTUAL_PORT=80
      # - HTTPS_METHOD=noredirect

  fpm:
    hostname: fpm.magento2.docker
    image: magento2-php:8.1-fpm
    build: ./8.1-fpm
    ports:
      - 9000
    links:
      - db
      - es
    volumes_from:
      - appdata
    env_file:
      - ./global.env

  db:
    image: mariadb:10.4.13
    ports:
      - 3306
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2
      - TERM=meh
  es:
    image: elasticsearch:7.17.8
    ports:
      - 9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - ELASTIC_PASSWORD=magento2
      - ELASTIC_USERNAME=magento2
      - node.name=es01
      - cluster.name=es_cluster
      - cluster.initial_master_nodes=es01

  cli:
    hostname: cli.magento2.docker
    image: magento2-php:8.1-cli
    build: ./8.1-cli
    links:
      - db
      - es
    volumes:
      - ~/.composer/cache:/root/.composer/cache
    volumes_from:
      - appdata
    env_file:
      - ./global.env
      - ./composer.env
    environment:
      - M2SETUP_INSTALL_DB=true
      - M2SETUP_DB_HOST=db
      - M2SETUP_DB_NAME=magento2
      - M2SETUP_DB_USER=magento2
      - M2SETUP_DB_PASSWORD=magento2
      - M2SETUP_BASE_URL=http://localhost/
      # - M2SETUP_SECURE_BASE_URL=https://localhost/
      - M2SETUP_BACKEND_FRONTNAME=admin
      - M2SETUP_ADMIN_FIRSTNAME=Admin
      - M2SETUP_ADMIN_LASTNAME=User
      - M2SETUP_ADMIN_EMAIL=dummy@gmail.com
      - M2SETUP_ADMIN_USER=admin
      - M2SETUP_ADMIN_PASSWORD=password1
      - M2SETUP_VERSION=2.4.*
      - M2SETUP_SEARCH_ENGINE=elasticsearch7
      - M2SETUP_ELASTICSEARCH_HOST=es
      - M2SETUP_ELASTICSEARCH_PORT=9200
      - M2SETUP_ELASTICSEARCH_USERNAME=magento2
      - M2SETUP_ELASTICSEARCH_PASSWORD=magento2
      # - M2SETUP_USE_SAMPLE_DATA=true

  cron:
    image: magento2-php:8.1-cli
    hostname: magento2-cron.docker
    command: run-cron
    env_file:
      - ./global.env    
    environment:
      - ENABLE_SENDMAIL=true
    volumes_from:
      - appdata
    links:
      - db
      - es

  appdata:
    image: tianon/true
    volumes:
      - ./magento:/var/www/magento

volumes:
  esdata:
    driver: local
  dbdata:
    driver: local